name: Build, Package, and Upload

on:
  - release
env:
  MAC_SHA: ""
  LINUX_x86_64_SHA-TAR: ""
  LINUX_x86_64_SHA-DEB: ""
  LINUX_x86_64_SHA-RPM: ""
  LINUX_AARCH64_SHA: ""
  LINUX_AARCH64_SHA-DEB: ""

jobs:
  PackageOnMacOS-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Package
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          swift build -c release
          mkdir LFSPointers-$TAG-macOS-amd64
          cp .build/release/LFSPointers LFSPointers-$TAG-macOS-amd64
          tar -czf LFSPointers-$TAG-macOS-amd64.tar.gz LFSPointers-$TAG-macOS-amd64
          export SHA256="$(cat LFSPointers-$TAG-macOS-amd64.tar.gz | shasum -a 256 | cut -d " " -f 1)"
          echo "MAC_SHA=$SHA256" >> $GITHUB_ENV
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LFSPointers-${{ github.event.release.tag_name }}-macOS-amd64.tar.gz
          asset_name: LFSPointers-${{ github.event.release.tag_name }}-macOS-amd64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
# Swift 5.3 Developer Snapshots aren't available yet.
  # PackageOnUbuntu-ARM:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: uraimo/run-on-arch-action@v1.1.0
  #       id: build-and-package
  #       env:
  #         TAG: ${{ github.event.release.tag_name }}
  #       with:
  #         architecture: aarch64
  #         distribution: ubuntu20.04
  #         githubToken: ${{ secrets.GITHUB_TOKEN }}
  #         run: |
  #           export DEBIAN_FRONTEND=noninteractive
  #           apt update -q
  #           apt install -q -y curl sudo
  #           curl -s https://packagecloud.io/install/repositories/swift-arm/release/script.deb.sh | sudo bash
  #           apt update -q -y
  #           apt install -q -y swift-lang
  #           swift build -c release --enable-test-discovery
  #           rm -f LFSPointers
  #           cp .build/release/LFSPointers .
  #           mkdir LFSPointers-$TAG-linux-arm64
  #           cp .build/release/LFSPointers LFSPointers-$TAG-linux-arm64
  #           tar -czf LFSPointers-${{ github.event.release.tag_name }}-linux-arm64.tar.gz LFSPointers-$TAG-linux-arm64
  #     - name: SetEnv
  #       run: |
  #         export SHA256=$(cat LFSPointers-$TAG-linux-arm64.tar.gz | shasum -a 256 | cut -d " " -f 1)
  #         echo "LINUX_AARCH64_SHA=$SHA256" >> $GITHUB_ENV
  #     - name: Upload Binaries
  #       uses: svenstaro/upload-release-action@v2
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         file: LFSPointers-${{ github.event.release.tag_name }}-linux-arm64.tar.gz
  #         file: LFSPointers-${{ github.event.release.tag_name }}-linux-arm64.tar.gz
  #         asset_name: LFSPointers-${{ github.event.release.tag_name }}-linux-arm64.tar.gz
  #         tag: ${{ github.ref }}
  #         overwrite: true
  #         body: ""
  #     - uses: kentik/pkg@v1.0.0-rc6
  #       with:
  #         name: LFSPointers
  #         version: ${{ github.event.release.tag_name }}
  #         arch: aarch64
  #         format: deb
  #         package: package.yaml
  #     - name: Hash Deb
  #       env:
  #         TAG: ${{ github.event.release.tag_name }}
  #       run: |
  #         export SHA256="$(cat LFSPointers_$TAG-arm64.deb | shasum -a 256 | cut -d " " -f 1)"
  #         echo "LINUX_AARCH64_SHA-DEB=$SHA256" >> $GITHUB_ENV
  #     - name: Upload Deb
  #       uses: svenstaro/upload-release-action@v2
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         file: ./*.deb
  #         tag: ${{ github.ref }}
  #         overwrite: true
  #         body: ""
  #         file_glob: true
  PackageOnUbuntu-x86_64:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-5.3-focal
    steps:
      - uses: actions/checkout@v2
      - name: Build and Package
        id: build-and-package
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          swift build -c release --enable-test-discovery --static-swift-stdlib -Xswiftc -static-executable
          rm -f LFSPointers
          cp .build/release/LFSPointers .
          mkdir LFSPointers-$TAG-linux-amd64
          cp .build/release/LFSPointers LFSPointers-$TAG-linux-amd64
          tar -czf LFSPointers-$TAG-linux-amd64.tar.gz LFSPointers-$TAG-linux-amd64
          export SHA256="$(cat LFSPointers-$TAG-linux-amd64.tar.gz | shasum -a 256 | cut -d " " -f 1)"
          echo "LINUX_x86_64_SHA-TAR=$SHA256" >> $GITHUB_ENV
      - uses: kentik/pkg@v1.0.0-rc6
        with:
          name: LFSPointers
          version: ${{ github.event.release.tag_name }}
          arch: x86_64
          format: deb
          package: package.yaml
      - uses: kentik/pkg@v1.0.0-rc6
        with:
          name: LFSPointers
          version: ${{ github.event.release.tag_name }}
          arch: x86_64
          format: rpm
          package: package.yaml
      - name: Hash Deb
        id: hashDeb
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          export SHA256="$(cat LFSPointers_$TAG-1_amd64.deb | shasum -a 256 | cut -d " " -f 1)"
          echo "LINUX_x86_64_SHA-DEB=$SHA256" >> $GITHUB_ENV
          export SHA256="$(cat LFSPointers-$TAG-1.x86_64.rpm | shasum -a 256 | cut -d " " -f 1)"
          echo "LINUX_x86_64_SHA-RPM=$SHA256" >> $GITHUB_ENV
      - name: Upload Deb
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.deb
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
          file_glob: true
      - name: Upload RPM
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.rpm
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
          file_glob: true

  UpdateRelease:
    needs: [PackageOnMacOS-x86_64, PackageOnUbuntu-x86_64]
    runs-on: ubuntu-latest
    steps:
      - name: Add SHA256
        uses: tubone24/update_release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            # Hashes

            LFSPointers-${{ github.event.release.tag_name }}-macOS-amd64.tar.gz

            ```
            ${{ env.MAC_SHA }}
            ```

            LFSPointers-${{ github.event.release.tag_name }}-linux-amd64.tar.gz

            ```
            ${{ env.LINUX_x86_64_SHA-TAR }}
            ```

            LFSPointers_${{ github.event.release.tag_name }}-1_amd64.deb

            ```
            ${{ env.LINUX_x86_64_SHA-DEB }}
            ```

            LFSPointers_${{ github.event.release.tag_name }}-1.x86_64.rpm

            ```
            ${{ env.LINUX_x86_64_SHA-RPM }}
            ```